from panda3d.core import Vec3
VIEWPORT_3D         = 0
VIEWPORT_2D_FRONT   = 6
VIEWPORT_2D_SIDE    = 7
VIEWPORT_2D_TOP     = 8
VIEWPORT_AXIS_UNUSED = {VIEWPORT_2D_FRONT: 0,
 VIEWPORT_2D_SIDE: 1,
 VIEWPORT_2D_TOP: 2}
VIEWPORT_VIEW_HPR = {VIEWPORT_2D_FRONT: Vec3(90, 0, 0),
 VIEWPORT_2D_SIDE: Vec3(0, 0, 0),
 VIEWPORT_2D_TOP: Vec3(0, -90, 0)}
VIEWPORT_NAMES = {VIEWPORT_2D_FRONT: "2D Front",
 VIEWPORT_2D_SIDE: "2D Side",
 VIEWPORT_2D_TOP: "2D Top"}
