# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/asset_browser.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssetBrowser(object):
    def setupUi(self, AssetBrowser):
        AssetBrowser.setObjectName("AssetBrowser")
        AssetBrowser.resize(902, 670)
        self.gridLayout = QtWidgets.QGridLayout(AssetBrowser)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(AssetBrowser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.frame = QtWidgets.QFrame(AssetBrowser)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.folderView = QtWidgets.QTreeWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderView.sizePolicy().hasHeightForWidth())
        self.folderView.setSizePolicy(sizePolicy)
        self.folderView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.folderView.setColumnCount(1)
        self.folderView.setObjectName("folderView")
        self.folderView.headerItem().setText(0, "1")
        self.horizontalLayout.addWidget(self.folderView)
        self.fileView = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileView.sizePolicy().hasHeightForWidth())
        self.fileView.setSizePolicy(sizePolicy)
        self.fileView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileView.setIconSize(QtCore.QSize(96, 96))
        self.fileView.setTextElideMode(QtCore.Qt.ElideLeft)
        self.fileView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.fileView.setMovement(QtWidgets.QListView.Static)
        self.fileView.setFlow(QtWidgets.QListView.LeftToRight)
        self.fileView.setProperty("isWrapping", True)
        self.fileView.setResizeMode(QtWidgets.QListView.Adjust)
        self.fileView.setLayoutMode(QtWidgets.QListView.Batched)
        self.fileView.setGridSize(QtCore.QSize(128, 128))
        self.fileView.setViewMode(QtWidgets.QListView.IconMode)
        self.fileView.setUniformItemSizes(True)
        self.fileView.setWordWrap(True)
        self.fileView.setSelectionRectVisible(True)
        self.fileView.setItemAlignment(QtCore.Qt.AlignCenter)
        self.fileView.setObjectName("fileView")
        self.horizontalLayout.addWidget(self.fileView)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)
        self.leFileFilter = QtWidgets.QLineEdit(AssetBrowser)
        self.leFileFilter.setObjectName("leFileFilter")
        self.gridLayout.addWidget(self.leFileFilter, 1, 1, 1, 1)

        self.retranslateUi(AssetBrowser)
        self.buttonBox.accepted.connect(AssetBrowser.accept)
        self.buttonBox.rejected.connect(AssetBrowser.reject)
        QtCore.QMetaObject.connectSlotsByName(AssetBrowser)

    def retranslateUi(self, AssetBrowser):
        _translate = QtCore.QCoreApplication.translate
        AssetBrowser.setWindowTitle(_translate("AssetBrowser", "Asset Browser"))
        self.fileView.setSortingEnabled(False)
        self.leFileFilter.setPlaceholderText(_translate("AssetBrowser", "(Asset File Filter)"))
