# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelEditor(object):
    def setupUi(self, LevelEditor):
        LevelEditor.setObjectName("LevelEditor")
        LevelEditor.resize(1083, 818)
        LevelEditor.setMinimumSize(QtCore.QSize(640, 480))
        LevelEditor.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        LevelEditor.setDocumentMode(False)
        LevelEditor.setTabShape(QtWidgets.QTabWidget.Rounded)
        LevelEditor.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(LevelEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.documentTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.documentTabs.setDocumentMode(True)
        self.documentTabs.setTabsClosable(True)
        self.documentTabs.setMovable(True)
        self.documentTabs.setObjectName("documentTabs")
        self.gridLayout.addWidget(self.documentTabs, 0, 0, 1, 1)
        LevelEditor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LevelEditor)
        self.statusbar.setObjectName("statusbar")
        LevelEditor.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(LevelEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 22))
        self.menubar.setObjectName("menubar")
        LevelEditor.setMenuBar(self.menubar)
        self.leftBar = QtWidgets.QToolBar(LevelEditor)
        self.leftBar.setObjectName("leftBar")
        LevelEditor.addToolBar(QtCore.Qt.LeftToolBarArea, self.leftBar)

        self.retranslateUi(LevelEditor)
        self.documentTabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(LevelEditor)

    def retranslateUi(self, LevelEditor):
        _translate = QtCore.QCoreApplication.translate
        LevelEditor.setWindowTitle(_translate("LevelEditor", "TTSP Editor"))
        self.leftBar.setWindowTitle(_translate("LevelEditor", "toolBar_2"))
